namespace SAT.MODELS.Enums
{
    public enum ExportacaoTipoEnum
    {
        ORDEM_SERVICO,
        EQUIPAMENTO_CONTRATO,
        ACAO,
        AUTORIZADA,
        TECNICO,
        ACAO_COMPONENTE,
        CIDADE,
        CLIENTE,
        CLIENTEPECA,
        CLIENTEPECAGENERICA,
        CLIENTEBANCADA,
        CONTRATO,
        DEFEITO,
        EQUIPAMENTO,
        GRUPOEQUIPAMENTO,
        TIPOEQUIPAMENTO,
        DEFEITOCOMPONENTE,
        EQUIPAMENTOMODULO,
        FERIADO,
        FERRAMENTATECNICO,
        FORMAPAGAMENTO,
        LIDERTECNICO,
        LOCALATENDIMENTO,
        PECA,
        USUARIO,
        REGIAO,
        REGIAOAUTORIZADA,
        FILIAL
    }
}