namespace SAT.MODELS.Enums
{
    public enum IndicadorAgrupadorEnum
    {
        CLIENTE,
        FILIAL,
        STATUS_SERVICO,
        TIPO_INTERVENCAO,
        DATA,
        TECNICO_PERCENT_REINCIDENTES,
        TECNICO_QNT_CHAMADOS_REINCIDENTES,
        EQUIPAMENTO_PERCENT_REINCIDENTES,
        TECNICO_PERCENT_SPA,
        TECNICO_QNT_CHAMADOS_SPA,
        TECNICO_PERCENT_PENDENTES,
        TECNICO_QNT_CHAMADOS_PENDENTES,
        TOP_PECAS_FALTANTES,
        NOVAS_CADASTRADAS,
        NOVAS_LIBERADAS,
        REGIAO,
        TOP_PECAS_MAIS_FALTANTES
    }
}