namespace SAT.MODELS.Enums
{
    public enum PontoUsuarioDataMotivoDivergenciaEnum
    {
        FALTA_MARCACAO = 1,
        OUTROS = 2,
        AUSENCIA_DISPOSITIVO_MOVEL = 3,
        AUSENCIA_INTERVALO = 4,
        INTERVALO_MAXIMO_DE_2_HORAS_EXCEDIDO = 5,
        INTERVALO_MINIMO_1_HORA_NAO_REALIZADO = 6,
        HORA_EXTRA_SEM_AVISO_PREVIO = 7,
        RAT_SEM_PONTO = 8,
        RAT_ANTES_PRIMEIRO_PONTO = 9,
        RAT_APOS_ULTIMO_PONTO = 10,
        INTERVALO_RAT_MENOR_PONTO = 11,
        INTERVALO_RAT_DIFERENTE_PONTO = 12
    }
}