using System.Linq;
using SAT.MODELS.Entities.Constants;
using SAT.MODELS.Entities.Params;

namespace SAT.SERVICES.Services
{
    public partial class ExportacaoService
    {
        protected void GerarPlanilhaInstalacao(InstalacaoParameters parameters)
        {
            var instalacoes = _instalacaoRepo.ObterPorParametros(parameters);
            var viewUnificada = _instalacaoRepo.ObterViewPorInstalacao(instalacoes.Select(instalacao => instalacao.CodInstalacao).ToArray());

            var sheet = viewUnificada.Select(v =>
                            new
                            {
                                CodInstalacao = v.CodInstalacao.HasValue ? v.CodInstalacao.Value.ToString() : Constants.NENHUM_REGISTRO,
                                Filial = v.Filial ?? Constants.NENHUM_REGISTRO,
                                Autorizada = v.Autorizada ?? Constants.NENHUM_REGISTRO,
                                Regiao = v.Regiao ?? Constants.NENHUM_REGISTRO,
                                LoteImportacao = v.LoteImportacao ?? Constants.NENHUM_REGISTRO,
                                DataRemessa = v.DataRemessa.HasValue ? v.DataRemessa.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                Contrato = v.Contrato ?? Constants.NENHUM_REGISTRO,
                                PedidoCompra = v.PedidoCompra ?? Constants.NENHUM_REGISTRO,
                                SuperE = v.SuperE ?? Constants.NENHUM_REGISTRO,
                                CMA = v.CMA ?? Constants.NENHUM_REGISTRO,
                                Lote = v.Lote ?? Constants.NENHUM_REGISTRO,
                                Terceirizado = v.Terceirizado ?? Constants.NENHUM_REGISTRO,
                                TipoDep = v.TipoDep ?? Constants.NENHUM_REGISTRO,
                                TipoNovo = v.TipoNovo ?? Constants.NENHUM_REGISTRO,
                                NSerie = v.NSerie ?? Constants.NENHUM_REGISTRO,
                                NumeroTAANovo = v.NumeroTAANovo ?? Constants.NENHUM_REGISTRO,
                                PrefixoSB = v.PrefixoSB ?? Constants.NENHUM_REGISTRO,
                                Dependencia = v.Dependencia ?? Constants.NENHUM_REGISTRO,
                                CNPJ = v.CNPJ ?? Constants.NENHUM_REGISTRO,
                                Logradouro = v.Logradouro ?? Constants.NENHUM_REGISTRO,
                                Municipio = v.Municipio ?? Constants.NENHUM_REGISTRO,
                                UF = v.UF ?? Constants.NENHUM_REGISTRO,
                                CEP = v.CEP ?? Constants.NENHUM_REGISTRO,
                                PrevisaoEntrega = v.PrevisaoEntrega.HasValue ? v.PrevisaoEntrega.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtConfirmadaEntrega = v.DtConfirmadaEntrega.HasValue ? v.DtConfirmadaEntrega.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                NFRemessa = v.NFRemessa ?? Constants.NENHUM_REGISTRO,
                                NFRemessaDataExpedicao = v.NFRemessaDataExpedicao.HasValue ? v.NFRemessaDataExpedicao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtExpedicao = v.DtExpedicao.HasValue ? v.DtExpedicao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                TransportadoraEntrega = v.TransportadoraEntrega ?? Constants.NENHUM_REGISTRO,
                                AgEntrega = v.AgEntrega ?? Constants.NENHUM_REGISTRO,
                                NomeLocalEntrega = v.NomeLocalEntrega ?? Constants.NENHUM_REGISTRO,
                                RecebimentoDocumentacaoInstalacao = v.RecebimentoDocumentacaoInstalacao.HasValue ? v.RecebimentoDocumentacaoInstalacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                FaturaTranspReEntrega = v.FaturaTranspReEntrega ?? Constants.NENHUM_REGISTRO,
                                DtReEntrega = v.DtReEntrega.HasValue ? v.DtReEntrega.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ResponsavelRecebReEntrega = v.ResponsavelRecebReEntrega ?? Constants.NENHUM_REGISTRO,
                                DataEntregaConfirmacao = v.DataEntregaConfirmacao.HasValue ? v.DataEntregaConfirmacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ResponsavelRecebimento = v.ResponsavelRecebReEntrega ?? Constants.NENHUM_REGISTRO,
                                MatResponsavelRecebimento = v.MatResponsavelRecebimento ?? Constants.NENHUM_REGISTRO,
                                BorderoTranspRecebido = v.BorderoTranspRecebido ?? Constants.NENHUM_REGISTRO,
                                BorderoTranspConferido = v.BorderoTranspConferido ?? Constants.NENHUM_REGISTRO,
                                NFRemessaConferida = v.NFRemessaConferida ?? Constants.NENHUM_REGISTRO,
                                PrevisaoInstalacao = v.PrevisaoInstalacao.HasValue ? v.PrevisaoInstalacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtAgendadaInstalacao = v.DtAgendadaInstalacao.HasValue ? v.DtAgendadaInstalacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                OS = v.OS.HasValue ? v.OS.Value.ToString() : Constants.NENHUM_REGISTRO,
                                DataHoraOS = v.DataHoraOS.HasValue ? v.DataHoraOS.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                StatusOS = v.StatusOS ?? Constants.NENHUM_REGISTRO,
                                RAT = v.RAT ?? Constants.NENHUM_REGISTRO,
                                AgInstalacao = v.AgInstalacao ?? Constants.NENHUM_REGISTRO,
                                NomeLocalInstalacao = v.NomeLocalInstalacao ?? Constants.NENHUM_REGISTRO,
                                DtInstalacao = v.DtInstalacao.HasValue ? v.DtInstalacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                QtdParabold = v.QtdParabold.HasValue ? v.QtdParabold.Value.ToString() : Constants.NENHUM_REGISTRO,
                                EquipamentoRebaixado = v.EquipamentoRebaixado ?? Constants.NENHUM_REGISTRO,
                                ResponsavelInstalacaoBanco = v.ResponsavelInstalacaoBanco ?? Constants.NENHUM_REGISTRO,
                                MatResponsavelInstalacaoBanco = v.MatResponsavelInstalacaoBanco ?? Constants.NENHUM_REGISTRO,
                                TermoAceite = v.TermoAceite ?? Constants.NENHUM_REGISTRO,
                                TermoDescaracterizacao = v.TermoDescaracterizacao ?? Constants.NENHUM_REGISTRO,
                                Laudo = v.Laudo ?? Constants.NENHUM_REGISTRO,
                                RE5330 = v.RE5330 ?? Constants.NENHUM_REGISTRO,
                                RATEntregue = v.RATEntregue ?? Constants.NENHUM_REGISTRO,
                                FornecedorTradeIn1 = v.FornecedorTradeIn1 ?? Constants.NENHUM_REGISTRO,
                                FornecedorTradeIn2 = v.FornecedorTradeIn2 ?? Constants.NENHUM_REGISTRO,
                                NumBemTradeIn = v.NumBemTradeIn ?? Constants.NENHUM_REGISTRO,
                                FornecedorBemTradeIn = v.FornecedorBemTradeIn ?? Constants.NENHUM_REGISTRO,
                                TipoBemTradeIn = v.TipoBemTradeIn ?? Constants.NENHUM_REGISTRO,
                                NFTradeIn1 = v.NFTradeIn1 ?? Constants.NENHUM_REGISTRO,
                                NFTradeIn2 = v.NFTradeIn2 ?? Constants.NENHUM_REGISTRO,
                                DataNFTradeIn1 = v.DataNFTradeIn1.HasValue ? v.DataNFTradeIn1.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DataNFTradeIn2 = v.DataNFTradeIn2.HasValue ? v.DataNFTradeIn2.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorTradeIn1 = string.Format("{0:C}", v.ValorTradeIn1),
                                ValorTradeIn2 = string.Format("{0:C}", v.ValorTradeIn2),
                                ValorKmTradeIn1 = string.Format("{0:C}", v.ValorKmTradeIn1),
                                ValorKmTradeIn2 = string.Format("{0:C}", v.ValorKmTradeIn2),
                                DistanciaKmTradeIn1 = string.Format("{0:C}", v.DistanciaKmTradeIn1),
                                DistanciaKmTradeIn2 = string.Format("{0:C}", v.DistanciaKmTradeIn2),
                                ValorTotalTradeIn1 = string.Format("{0:C}", v.ValorTotalTradeIn1),
                                ValorTotalTradeIn2 = string.Format("{0:C}", v.ValorTotalTradeIn2),
                                TransportadoraTradeIn = v.TransportadoraTradeIn ?? Constants.NENHUM_REGISTRO,
                                DtPrevRecolhimentoTradeIn = v.DtPrevRecolhimentoTradeIn.HasValue ? v.DtPrevRecolhimentoTradeIn.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DataRetiradaBemTradeIn = v.DataRetiradaBemTradeIn.HasValue ? v.DataRetiradaBemTradeIn.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                Romaneio = v.Romaneio ?? Constants.NENHUM_REGISTRO,
                                NFTranspTradeIn = v.NFTranspTradeIn ?? Constants.NENHUM_REGISTRO,
                                DataNFTransTradeIn = v.DataNFTransTradeIn.HasValue ? v.DataNFTransTradeIn.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorRecolhimentoTradeIn = string.Format("{0:C}", v.ValorRecolhimentoTradeIn),
                                ReponsavelBancoAcompanhamentoTradeIn = v.ReponsavelBancoAcompanhamentoTradeIn ?? Constants.NENHUM_REGISTRO,
                                MatriculaRespBancoAcompanhamentoRecolhimento = v.MatriculaRespBancoAcompanhamentoRecolhimento ?? Constants.NENHUM_REGISTRO,
                                FornecedorCompraTradeIn = v.FornecedorCompraTradeIn ?? Constants.NENHUM_REGISTRO,
                                NFVendaTradeIn = v.NFVendaTradeIn ?? Constants.NENHUM_REGISTRO,
                                DtNFVendaTradeIn = v.DtNFVendaTradeIn.HasValue ? v.DtNFVendaTradeIn.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorVendaTradeIn = string.Format("{0:C}", v.ValorVendaTradeIn),
                                NFInstalacaoAutorizada = v.NFInstalacaoAutorizada ?? Constants.NENHUM_REGISTRO,
                                DtNFInstalacaoAutorizada = v.DtNFInstalacaoAutorizada.HasValue ? v.DtNFInstalacaoAutorizada.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                NFVenda = v.NFVenda.HasValue ? v.NFVenda.Value.ToString() : Constants.NENHUM_REGISTRO,
                                NFVendaDataEmissao = v.NFVendaDataEmissao.HasValue ? v.NFVendaDataEmissao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtEnvioNFVenda = v.DtEnvioNFVenda.HasValue ? v.DtEnvioNFVenda.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtRecebimentoNFVenda = v.DtRecebimentoNFVenda.HasValue ? v.DtRecebimentoNFVenda.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DtPagtoInstalacao = v.DtPagtoInstalacao.HasValue ? v.DtPagtoInstalacao.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                VlrPagtoInstalacao = string.Format("{0:C}", v.VlrPagtoInstalacao),
                                Bordero = v.Bordero.HasValue ? v.Bordero.Value.ToString() : Constants.NENHUM_REGISTRO,
                                DTVencimentoBordero100Perc = v.DTVencimentoBordero100Perc.HasValue ? v.DTVencimentoBordero100Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DTEntregaBordero100Perc = v.DTEntregaBordero100Perc.HasValue ? v.DTEntregaBordero100Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DTVencimentoBordero90Perc = v.DTVencimentoBordero90Perc.HasValue ? v.DTVencimentoBordero90Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DTEntregaBordero90Perc = v.DTEntregaBordero90Perc.HasValue ? v.DTEntregaBordero90Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DTVencimentoBordero10Perc = v.DTVencimentoBordero10Perc.HasValue ? v.DTVencimentoBordero10Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                DTEntregaBordero10Perc = v.DTEntregaBordero10Perc.HasValue ? v.DTEntregaBordero10Perc.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorFrete1 = string.Format("{0:C}", v.ValorFrete1),
                                FaturaFrete1 = v.FaturaFrete1 ?? Constants.NENHUM_REGISTRO,
                                CteFrete1 = v.CteFrete1 ?? Constants.NENHUM_REGISTRO,
                                DataFaturaFrete1 = v.DataFaturaFrete1.HasValue ? v.DataFaturaFrete1.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorFrete2 = string.Format("{0:C}", v.ValorFrete2),
                                FaturaFrete2 = v.FaturaFrete2 ?? Constants.NENHUM_REGISTRO,
                                CteFrete2 = v.CteFrete2 ?? Constants.NENHUM_REGISTRO,
                                DataFaturaFrete2 = v.DataFaturaFrete2.HasValue ? v.DataFaturaFrete1.Value.ToString("dd/MM/yy HH:mm") : Constants.NENHUM_REGISTRO,
                                ValorExtraFrete = string.Format("{0:C}", v.ValorExtraFrete),
                                DDD = v.DDD ?? Constants.NENHUM_REGISTRO,
                                Telefone1 = v.Telefone1 ?? Constants.NENHUM_REGISTRO,
                                Redestinacao = v.Redestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoPrefixoRedestinacao = v.AntigoPrefixoRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoSbRedestinacao = v.AntigoSbRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoNomeDependenciaRedestinacao = v.AntigoNomeDependenciaRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoUfRedestinacao = v.AntigoUfRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoTipoDependenciaRedestinacao = v.AntigoTipoDependenciaRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoPedidoCompraRedestinacao = v.AntigoPedidoCompraRedestinacao ?? Constants.NENHUM_REGISTRO,
                                AntigoProtocoloCdo = v.AntigoProtocoloCdo ?? Constants.NENHUM_REGISTRO,
                                NovoProtocoloCdo = v.NovoProtocoloCdo ?? Constants.NENHUM_REGISTRO,
                            });

            var wsOs = Workbook.Worksheets.Add("Instalacoes");
            wsOs.Cell(2, 1).Value = sheet;
            WriteHeaders(sheet.FirstOrDefault(), wsOs);
        }
    }
}