import { Meta, QueryStringParameters } from "./generic.types";

export interface ORStatus {
    codStatus: number;
    descStatus: string;
    indAtivo: number | null;
    abrev: string;
}

export interface ORStatusData extends Meta {
    items: ORStatus[];
};

export interface ORStatusParameters extends QueryStringParameters {
    abrev?: string;
}

export const orStatusConst = {
	AGUARDANDO_ENVIO: 1,
    EM_TRATATIVA_DIVERGENCIA: 2,
    REPARADOR_EXTERNO: 3,
    REPARADOR_LABORATORIO: 4,
    EXPEDIDO: 5,
    DEVOLUCAO_FILIAL: 6,
    LABORATORIO_AGUARD_REPARO: 7,
    DEVOLUCAO_SEM_REPARO: 8,
    GERACAO_ORCAMENTO: 9,
    ENVIO_ORCAMENTO: 10,
    AGUARDANDO_RETORNO_ORC: 11,
    DEVOLUCAO_CLIENTE: 12,
    EM_REPARO: 13,
    CONFERENCIA_LABORATORIO: 14,
    AGUARDANDO_REPARO: 15,
    TRANSFERIDO_TECNICO: 16,
    REPARO_N1_N2_CHECKLIST_ATUALIZACAO: 17,
    SOLICITA_PECA_AGUARDANDO_PECA: 18,
    REPARO_AVANCADO: 19,
    CHECKLIST_FINAL: 20,
    RETRABALHO: 21,
    AVALIAR_DEFINIR_DESTINO: 22,
    TRANSFERENCIA_CD_ESTOQUE: 23,
    CONTROLE_DE_TEMPO_DE_REPARO: 24,
    AGUARDANDO_EXPEDICAO: 25,
    RECEBIMENTO_LOGISTICA: 26,
    REAPROVEITAMENTO_SUCATA: 28,
    DEVOLUCAO_SEM_REPAROS: 29,
    PARCIAL_FALTA_DE_INSUMO: 30,
    RECEBIDO_BAIXA: 31,
    DEVOLUCAO_LOGISTICA: 32,
    CANCELADO: 33,
    LOGISTICA_EM_TRÂNSITO: 34,
    NAO_INFORMADO: 35,
    OR_ENCERRADA: 36,
    SUPORTE: 37,
    PECA_LIBERADA: 38,
    LOGISTICA: 39,
    AGUARDANDO_TRANSFERENCIA: 40,
    DEVOLUCAO_FILIAL_DIVERGENCIA: 41
}