import { Meta, QueryStringParameters } from "./generic.types";

export class Perfil
{
    codPerfil: number;
    nomePerfil: string;
    descPerfil: string;
    indResumo?: number;
    codSistema?: number;
    indAbreChamado?: number;
}

export interface PerfilData extends Meta
{
    items: Perfil[];
};

export interface PerfilParameters extends QueryStringParameters
{
    codPerfil?: number;
};

export enum PerfilEnum {
    PV_CENTRAL_ATENDENTE = 2,
    ADM_DO_SISTEMA = 3,
    FILIAL_COORDENADOR = 5,
    FÁBRICA_GERENTE = 6,
    FILIAL_ATENDENTE_C_REGISTRO_DE_PONTO_NO_SAT = 7,
    FINANCEIRO_COORDENADOR = 16,
    AUTORIZADA_ON_SITE = 18,
    PV_COORDENADOR_DE_CONTRATO = 29,
    LOGÍSTICA_ESTOQUISTA_C_REGISTRO_DE_PONTO_NO_SAT = 30,
    LOGÍSTICA_DEPTO = 31,
    FILIAL_SUPORTE_TÉCNICO = 32,
    CLIENTE = 34,
    FILIAL_TECNICO_DE_CAMPO = 35,
    BANCADA_ATENDENTE = 37,
    BANCADA_EXPEDICAO = 39,
    CLIENTE_BÁSICO = 40,
    FÁBRICA_EXPEDIÇÃO = 41,
    PONTO_COLABORADOR = 42,
    PONTO_COORDENADOR_OU_RH = 44,
    ADMINISTRADOR_BASICO = 46,
    UTILIZADOR_CUBO = 47,
    VPP_COMPRADOR = 48,
    VPP_GERENCIADOR_DE_CUSTOS = 49,
    VPP_PCP = 51,
    VPP_CONTROLADOR_PEDIDOS_PEÇAS = 52,
    VPP_ADMINISTRADOR = 55,
    VPP_VENDEDOR = 56,
    FILIAL_ADMINISTRATIVO = 57,
    PV_HELP_DESK_ATENDENTE = 58,
    FINANCEIRO_ADMINISTRATIVO = 59,
    LOGÍSTICA_COORDENADOR = 60,
    BANCADA_TECNICO = 61,
    FILIAL_ATENDENTE_S_REGISTRO_DE_PONTO_NO_SAT = 62,
    BANCADA_COORDENADOR = 63,
    TREINAMENTO = 64,
    PONTO_FINANCEIRO = 65,
    CONTABILIDADE_PAGAMENTOS = 66,
    CONTABILIDADE_NF = 67,
    LOGÍSTICA_ESTOQUISTA_S_REGISTRO_DE_PONTO_NO_SAT = 68,
    SUPORTE_DE_EXPORTAÇÃO = 69,
    FINANCEIRO_COORDENADOR_PONTO = 70,
    PARCEIROS = 71,
    PV_CENTRAL_ATENDENTE_BRB = 72,
    COORDENADOR_POS = 73,
    PONTO_COLABORADOR_CONTRATO = 74,
    FILIAIS_SUPERVISOR = 75,
    FILIAIS_E_LABORATORIO_SUPERVISOR = 76,
    PV_IMPLANTAÇÃO = 77,
    VISUALIZADOR_GPS = 78,
    FILIAL_SUPORTE_TÉCNICO_CAMPO = 79,
    FILIAL_LIDER_DE_SETOR = 80,
    CLIENTE_BASICO_S_ABERTURA = 81,
    FILIAL_LIDER_C_FUNCOES_COORDENADOR = 82,
    RASTREAMENTO = 83,
    FILIAL_TECNICO_DE_CAMPO_C_CHAMADOS = 84,
    ANALISTA_DE_OPERACOES_TSE = 85,
    LOGÍSTICA_COORDENADOR_ESTOQUISTA = 86,
    CLIENTE_CORREIOS = 87,
    AUTORIZADA_ON_SITE_POS = 88,
    PLANTÃO_HELP_DESK = 89,
    CLIENTE_BASICO_C_RESTRICOES = 90,
    PRODUÇÃO_POS = 91,
    LABORATÓRIO_POS = 92,
    CLIENTE_BASICO_BIOMETRIA = 93,
    ASSISTENTE_LABORATÓRIO = 94,
    LOGISTICA_FILIAL_LAB = 95,
    HELP_DESK_POS = 96,
    CLIENTE_S_ABERTURA = 97,
    CLIENTE_PEÇAS_EXPORTAÇÃO = 98,
    PERTO_STORE = 99,
    FINANCEIRO_COORDENADOR_CREDITO = 100
}